app:
  adapters:
    worker-receiving-session-repository-adapter: "jpa"

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_ISSUER_URL} # responsible for verifying tokens

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        retry.backoff.ms: 1000
        spring.json.add.type.headers: false

springdoc:
  api-docs:
    path: /v3/api-docs/receiving-service # endpoint for gateway to get docs
  swagger-ui:
    enabled: false # for this service separately swagger is disabled

