app:
  adapters:
    worker-receiving-session-repository-adapter: "jpa"

  security:
    jwt:
      secret: ${JWT_SECRET}
      access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
      refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS}
      allowed-methods: ${CORS_ALLOWED_METHODS}
      allowed-headers: ${CORS_ALLOWED_HEADERS}
      allow-credentials: ${CORS_ALLOW_CREDENTIALS:false}
      max-age: ${CORS_MAX_AGE}

spring:

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        retry.backoff.ms: 1000
        spring.json.add.type.headers: false



springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true